using System.Text.Json.Serialization;

namespace MiraeNet.Core.Completion;

/// <summary>
///     <see cref="CompletionMessage" /> represents a single message in a conversation.
///     It is designed to be used as part of a collection to form a conversation
///     that serves as input for a Large Language Model (LLM) to generate chat completions.
/// </summary>
public class CompletionMessage
{
    /// <summary>
    ///     Gets or sets the role of the message in the conversation.
    ///     The role indicates whether the message is from the System, a User, or the Assistant.
    /// </summary>
    [JsonPropertyName("role")]
    public required CompletionMessageRole Role { get; set; }

    /// <summary>
    ///     Gets or sets the content of the message.
    ///     This is the actual text of the message sent or received in the conversation.
    /// </summary>
    [JsonPropertyName("content")]
    public required string Content { get; set; }

    /// <summary>
    ///     Gets or sets the optional name associated with the message.
    ///     This can be used to identify the specific user or system component sending the message.
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
}

/// <summary>
///     Enumerates the possible roles of a message in a conversation.
/// </summary>
public enum CompletionMessageRole
{
    /// <summary>
    ///     Indicates a message generated by the system.
    /// </summary>
    System,

    /// <summary>
    ///     Represents a message sent by the user.
    /// </summary>
    User,

    /// <summary>
    ///     Denotes a message from the assistant, typically in response to a user message.
    /// </summary>
    Assistant
}